---
- name: Install package
  apt: name=git state=present
  sudo: yes
- name: Config file
  template: src=gitconfig.j2 dest=~/.gitconfig
- name: Ignore file
  template: src=gitignore.j2 dest={{ git_ignore_file }}
